<?php
namespace WCPOS\WooCommercePOS\SquareTerminal\Tests\Includes;
use PHPUnit\Framework\TestCase; use WCPOS\WooCommercePOS\SquareTerminal\AjaxHandler;
final class CountingAdapter { public int $calls=0; public int $cancels=0; public array $last_create=array(); public function create_checkout(array $d): array { $this->calls++; $this->last_create=$d; return ['id'=>'chk','status'=>'PENDING','reference_id'=>$d['reference_id'],'payment_ids'=>[]]; } public function cancel_checkout(string $id): array { $this->cancels++; return ['id'=>$id,'status'=>'CANCELED','reference_id'=>null,'payment_ids'=>[]]; }}
final class AjaxHandlerTest extends TestCase { protected function setUp(): void { $GLOBALS['sqtwc_orders']=array(); $GLOBALS['sqtwc_current_user_can']=false; $GLOBALS['sqtwc_is_user_logged_in']=false; $GLOBALS['sqtwc_nonce_valid']=false; }
 public function test_create_checkout_rejects_before_side_effect_without_access(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $adapter=new CountingAdapter(); $result=(new AjaxHandler($adapter))->create_terminal_checkout(['order_id'=>99,'device_id'=>'D']); self::assertSame(403,$result['status']); self::assertSame(0,$adapter->calls); }
 public function test_create_checkout_requires_nonce_for_authenticated_staff_from_server_state(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $GLOBALS['sqtwc_current_user_can']=true; $GLOBALS['sqtwc_is_user_logged_in']=true; $GLOBALS['sqtwc_nonce_valid']=false; $result=(new AjaxHandler(new CountingAdapter()))->create_terminal_checkout(['order_id'=>99,'device_id'=>'D']); self::assertSame(403,$result['status']); }
 public function test_create_checkout_reuses_order_idempotency_key(): void { $order=new \SQTWC_Test_Order(99); $order->update_meta_data('_sqtwc_checkout_idempotency_key','idem'); $GLOBALS['sqtwc_orders'][99]=$order; $adapter=new CountingAdapter(); $result=(new AjaxHandler($adapter))->create_terminal_checkout(['order_id'=>99,'device_id'=>'D','order_key'=>'key']); self::assertSame(200,$result['status']); self::assertSame('idem',$adapter->last_create['idempotency_key']); }
 public function test_cancel_checkout_uses_order_access_and_adapter(): void { $order=new \SQTWC_Test_Order(99); $order->update_meta_data('_sqtwc_checkout_id','chk'); $order->update_meta_data('_sqtwc_checkout_idempotency_key','idem'); $GLOBALS['sqtwc_orders'][99]=$order; $adapter=new CountingAdapter(); $result=(new AjaxHandler($adapter))->cancel_terminal_checkout(['order_id'=>99,'order_key'=>'key']); self::assertSame(200,$result['status']); self::assertSame(1,$adapter->cancels); self::assertSame('CANCELED',$result['checkout']['status']); self::assertSame('',$order->get_meta('_sqtwc_checkout_idempotency_key')); }}
