<?php
namespace WCPOS\WooCommercePOS\SquareTerminal\Tests\Includes;
use PHPUnit\Framework\TestCase; use WCPOS\WooCommercePOS\SquareTerminal\{Gateway,Plugin};
final class GatewayTest extends TestCase { public function test_register_gateway_appends_class(): void { self::assertContains(Gateway::class, Gateway::register_gateway(['Other'])); }
 protected function tearDown(): void { unset($GLOBALS['wp']); }
 public function test_constructor_hooks_gateway_settings_save(): void { $GLOBALS['sqtwc_actions']=array(); $gateway=new Gateway(); self::assertContains([$gateway,'process_admin_options'],$GLOBALS['sqtwc_actions']['woocommerce_update_options_payment_gateways_sqtwc']); }
 public function test_gateway_renders_order_pay_fields_when_constructed_before_query_vars_exist(): void { unset($GLOBALS['wp']); $gateway=new Gateway(); $GLOBALS['wp']=(object)['query_vars'=>['order-pay'=>99]]; ob_start(); $gateway->payment_fields(); $html=(string) ob_get_clean(); self::assertTrue($gateway->has_fields()); self::assertStringContainsString('id="sqtwc-payment"',$html); self::assertStringContainsString('data-order-id="99"',$html); }
 public function test_gateway_omits_interactive_fields_before_standard_checkout_creates_an_order(): void { unset($GLOBALS['wp']); $gateway=new Gateway(); ob_start(); $gateway->payment_fields(); $html=(string) ob_get_clean(); self::assertFalse($gateway->has_fields()); self::assertSame('',$html); }
 public function test_terminal_device_options_are_gateway_settings_defaulting_off(): void { $gateway=new Gateway(); self::assertSame('checkbox',$gateway->form_fields['skip_receipt_screen']['type']); self::assertSame('no',$gateway->form_fields['skip_receipt_screen']['default']); self::assertSame('checkbox',$gateway->form_fields['collect_signature']['type']); self::assertSame('no',$gateway->form_fields['collect_signature']['default']); }
 public function test_plugin_registers_payment_and_webhook_entrypoints(): void { $GLOBALS['sqtwc_actions']=array(); (new Plugin())->init(); self::assertArrayHasKey('wp_ajax_sqtwc_create_terminal_checkout',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('wp_ajax_sqtwc_get_terminal_status',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('wp_ajax_sqtwc_cancel_terminal_checkout',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('wp_ajax_sqtwc_detach_terminal_checkout',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('woocommerce_order_status_changed',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('rest_api_init',$GLOBALS['sqtwc_actions']); (new Plugin())->register_rest_routes(); self::assertArrayHasKey('sqtwc/v1/webhook',$GLOBALS['sqtwc_rest_routes']); self::assertArrayHasKey('sqtwc/v1/pos-callback',$GLOBALS['sqtwc_rest_routes']); self::assertSame(['GET','POST'],$GLOBALS['sqtwc_rest_routes']['sqtwc/v1/pos-callback']['methods']); }
 public function test_process_payment_redirects_unpaid_to_order_pay_and_paid_to_thank_you(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $gateway=new Gateway(); $result=$gateway->process_payment(99); self::assertSame('success',$result['result']); self::assertStringContainsString('/checkout/order-pay/99/', $result['redirect']); $order->paid=true; $result=$gateway->process_payment(99); self::assertSame('/thank-you',$result['redirect']); }
 public function test_pos_app_mode_renders_handoff_button_without_terminal_controls(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['collection_method'=>'pos_app','environment'=>'production']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $html=Gateway::render_payment_ui(99); self::assertStringContainsString('id="sqtwc-pos-open"',$html); self::assertStringContainsString('data-amount="1234"',$html); self::assertStringNotContainsString('id="sqtwc-start-payment"',$html); self::assertStringNotContainsString('id="sqtwc-device-id"',$html); }
 public function test_pos_app_localized_data_contains_handoff_fields(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $GLOBALS['wp']=(object)['query_vars'=>['order-pay'=>99]]; $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['collection_method'=>'pos_app','environment'=>'production','pos_application_id'=>'sq0idp-AbCdEf1234567890_-xyZA','location_id'=>'LOC','skip_receipt_screen'=>'yes']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $data=Gateway::get_localized_payment_data(); self::assertSame('pos_app',$data['collectionMethod']); self::assertSame('sq0idp-AbCdEf1234567890_-xyZA',$data['posApplicationId']); self::assertSame(1234,$data['amount']); self::assertSame('USD',$data['currency']); self::assertSame(99,$data['orderId']); self::assertSame('key',$data['orderKey']); self::assertSame('LOC',$data['posLocationId']); self::assertTrue($data['skipReceipt']); }
 public function test_pos_app_does_not_localize_a_malformed_application_id(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $GLOBALS['wp']=(object)['query_vars'=>['order-pay'=>99]]; $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['collection_method'=>'pos_app','environment'=>'production','pos_application_id'=>'sq0idp-AbCdEf12','location_id'=>'LOC']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); self::assertSame('',Gateway::get_localized_payment_data()['posApplicationId']); }
 public function test_pos_app_checkout_blocks_a_malformed_application_id(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['collection_method'=>'pos_app','environment'=>'production','pos_application_id'=>'sq0idp-AbCdEf12','location_id'=>'LOC']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $html=Gateway::render_payment_ui(99); self::assertStringContainsString('id="sqtwc-pos-open" class="button button-primary" data-sqtwc-action="pos-open" disabled',$html); self::assertStringContainsString('Add a valid Square application ID',$html); }
 public function test_pos_app_rejects_an_application_id_with_a_trailing_newline(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $GLOBALS['wp']=(object)['query_vars'=>['order-pay'=>99]]; $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['collection_method'=>'pos_app','environment'=>'production','pos_application_id'=>"sq0idp-AbCdEf1234567890_-xyZA\n",'location_id'=>'LOC']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); self::assertSame('',Gateway::get_localized_payment_data()['posApplicationId']); $html=Gateway::render_payment_ui(99); self::assertStringContainsString('id="sqtwc-pos-open" class="button button-primary" data-sqtwc-action="pos-open" disabled',$html); $checklist=(new Gateway())->generate_pos_setup_checklist_html('pos_application_id',[]); self::assertStringNotContainsString('sqtwc-setup__step--done" data-step="3"',$checklist); }
 public function test_device_chooser_renders_both_options_and_checks_saved_value(): void { $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['collection_method'=>'pos_app']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $html=(new Gateway())->generate_device_chooser_html('collection_method',['title'=>'Which Square device do you use?']); self::assertStringContainsString('name="woocommerce_sqtwc_collection_method"',$html); self::assertStringContainsString('value="terminal"',$html); self::assertStringContainsString('value="pos_app" checked',$html); self::assertStringContainsString('Square Terminal',$html); self::assertStringContainsString('Square Reader',$html); }
 public function test_device_chooser_validation_defaults_unknown_values_to_terminal(): void { $gateway=new Gateway(); self::assertSame('terminal',$gateway->validate_collection_method_field('collection_method','unknown')); self::assertSame('pos_app',$gateway->validate_collection_method_field('collection_method','pos_app')); }
 public function test_pos_application_id_validation_trims_whitespace_and_quotes(): void { $gateway=new Gateway(); self::assertSame('sq0idp-store',$gateway->validate_pos_application_id_field('pos_application_id','  "sq0idp-store"  ')); self::assertSame('anything-else',$gateway->validate_pos_application_id_field('pos_application_id','anything-else')); }
 public function test_checklist_tracks_connected_and_application_id_progress(): void { $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['environment'=>'production','production_access_token'=>'token','pos_application_id'=>'sq0idp-AbCdEf1234567890_-xyZA','collection_method'=>'pos_app']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $html=(new Gateway())->generate_pos_setup_checklist_html('pos_application_id',['title'=>'Set up your Square Reader']); self::assertStringContainsString('sqtwc-setup__step--done" data-step="1"',$html); self::assertStringContainsString('sqtwc-setup__step--done" data-step="3"',$html); self::assertStringContainsString('name="woocommerce_sqtwc_pos_application_id"',$html); self::assertStringContainsString('id="sqtwc-pos-callback-url"',$html); self::assertStringContainsString('id="sqtwc-copy-pos-callback"',$html); self::assertStringContainsString('id="sqtwc-pos-validate-settings"',$html); self::assertStringContainsString('id="sqtwc-pos-validate-status"',$html); }
 public function test_bare_or_truncated_application_id_prefix_is_not_done(): void { $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['environment'=>'production','pos_application_id'=>'sq0idp-AbCdEf12','collection_method'=>'pos_app']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $html=(new Gateway())->generate_pos_setup_checklist_html('pos_application_id',[]); self::assertStringNotContainsString('sqtwc-setup__step--done" data-step="3"',$html); }
 public function test_checklist_leaves_unverified_steps_open(): void { $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['environment'=>'production','collection_method'=>'pos_app']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $html=(new Gateway())->generate_pos_setup_checklist_html('pos_application_id',['title'=>'Set up your Square Reader']); self::assertStringNotContainsString('sqtwc-setup__step--done" data-step="1"',$html); self::assertStringNotContainsString('sqtwc-setup__step--done" data-step="3"',$html); self::assertStringNotContainsString('data-step="4"><span class="sqtwc-setup__chip sqtwc-setup__chip--done"',$html); }
 public function test_reader_sandbox_banner_is_always_rendered_but_hidden_in_live_mode(): void { $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['environment'=>'sandbox','collection_method'=>'pos_app']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $sandbox_html=(new Gateway())->generate_pos_setup_checklist_html('pos_application_id',[]); self::assertStringContainsString('id="sqtwc-setup-sandbox-notice"',$sandbox_html); self::assertStringNotContainsString('class="sqtwc-setup__notice" style="display:none"',$sandbox_html); $GLOBALS['sqtwc_options']['woocommerce_sqtwc_settings']=['environment'=>'production','collection_method'=>'pos_app']; \WCPOS\WooCommercePOS\SquareTerminal\Settings::reset_cache_for_tests(); $live_html=(new Gateway())->generate_pos_setup_checklist_html('pos_application_id',[]); self::assertStringContainsString('class="sqtwc-setup__notice" style="display:none"',$live_html); }
 public function test_pos_setup_fields_use_custom_rows_without_standalone_callback(): void { $fields=(new Gateway())->form_fields; self::assertSame('device_chooser',$fields['collection_method']['type']); self::assertSame('Which Square device do you use?',$fields['collection_method']['title']); self::assertSame('pos_setup_checklist',$fields['pos_application_id']['type']); self::assertArrayNotHasKey('pos_callback_url',$fields); }
}
