<?php
namespace WCPOS\WooCommercePOS\SquareTerminal\Tests\Includes;
use PHPUnit\Framework\TestCase; use WCPOS\WooCommercePOS\SquareTerminal\{Gateway,Plugin};
final class GatewayTest extends TestCase { public function test_register_gateway_appends_class(): void { self::assertContains(Gateway::class, Gateway::register_gateway(['Other'])); }
 protected function tearDown(): void { unset($GLOBALS['wp']); }
 public function test_constructor_hooks_gateway_settings_save(): void { $GLOBALS['sqtwc_actions']=array(); $gateway=new Gateway(); self::assertContains([$gateway,'process_admin_options'],$GLOBALS['sqtwc_actions']['woocommerce_update_options_payment_gateways_sqtwc']); }
 public function test_gateway_renders_order_pay_fields_when_constructed_before_query_vars_exist(): void { unset($GLOBALS['wp']); $gateway=new Gateway(); $GLOBALS['wp']=(object)['query_vars'=>['order-pay'=>99]]; ob_start(); $gateway->payment_fields(); $html=(string) ob_get_clean(); self::assertTrue($gateway->has_fields()); self::assertStringContainsString('id="sqtwc-payment"',$html); self::assertStringContainsString('data-order-id="99"',$html); }
 public function test_gateway_omits_interactive_fields_before_standard_checkout_creates_an_order(): void { unset($GLOBALS['wp']); $gateway=new Gateway(); ob_start(); $gateway->payment_fields(); $html=(string) ob_get_clean(); self::assertFalse($gateway->has_fields()); self::assertSame('',$html); }
 public function test_terminal_device_options_are_gateway_settings_defaulting_off(): void { $gateway=new Gateway(); self::assertSame('checkbox',$gateway->form_fields['skip_receipt_screen']['type']); self::assertSame('no',$gateway->form_fields['skip_receipt_screen']['default']); self::assertSame('checkbox',$gateway->form_fields['collect_signature']['type']); self::assertSame('no',$gateway->form_fields['collect_signature']['default']); }
 public function test_plugin_registers_payment_and_webhook_entrypoints(): void { $GLOBALS['sqtwc_actions']=array(); (new Plugin())->init(); self::assertArrayHasKey('wp_ajax_sqtwc_create_terminal_checkout',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('wp_ajax_sqtwc_get_terminal_status',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('wp_ajax_sqtwc_cancel_terminal_checkout',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('wp_ajax_sqtwc_detach_terminal_checkout',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('woocommerce_order_status_changed',$GLOBALS['sqtwc_actions']); self::assertArrayHasKey('rest_api_init',$GLOBALS['sqtwc_actions']); (new Plugin())->register_rest_routes(); self::assertArrayHasKey('sqtwc/v1/webhook',$GLOBALS['sqtwc_rest_routes']); }
 public function test_process_payment_redirects_unpaid_to_order_pay_and_paid_to_thank_you(): void { $order=new \SQTWC_Test_Order(99); $GLOBALS['sqtwc_orders'][99]=$order; $gateway=new Gateway(); $result=$gateway->process_payment(99); self::assertSame('success',$result['result']); self::assertStringContainsString('/checkout/order-pay/99/', $result['redirect']); $order->paid=true; $result=$gateway->process_payment(99); self::assertSame('/thank-you',$result['redirect']); }}
