<?php
/**
 * Generate the scoped vendor autoloader.
 *
 * The namespace map is derived from Composer's own generated autoload data
 * rather than hand-maintained, so adding a runtime dependency cannot silently
 * leave its classes unloadable in the distributed build. The generated loader
 * is then smoke-tested in a subprocess; a failure here fails the build.
 *
 * @package WCPOS\WooCommercePOS\SquareTerminal
 */

$vendor_scoped = __DIR__ . '/../vendor_scoped';
$composer_dir  = $vendor_scoped . '/composer';

if ( ! is_dir( $composer_dir ) ) {
	fwrite( STDERR, "Scoped vendor not found: {$composer_dir}\n" );
	exit( 1 );
}

/**
 * Load a Composer autoload map, tolerating absence.
 *
 * @param string $file Map file.
 * @return array<mixed>
 */
function sqtwc_load_map( string $file ): array {
	return is_file( $file ) ? (array) require $file : array();
}

$psr4  = sqtwc_load_map( $composer_dir . '/autoload_psr4.php' );
$files = sqtwc_load_map( $composer_dir . '/autoload_files.php' );

// Keep only namespaces whose directories exist inside vendor_scoped. This drops
// dev-only packages and the plugin's own (unprefixed) namespace.
$real_base = realpath( $vendor_scoped );
$map       = array();
foreach ( $psr4 as $namespace => $dirs ) {
	foreach ( (array) $dirs as $dir ) {
		$real = realpath( $dir );
		if ( false === $real || 0 !== strncmp( $real, $real_base, strlen( $real_base ) ) ) {
			continue;
		}
		$map[ $namespace ][] = substr( $real, strlen( $real_base ) );
	}
}

// Longest namespace first so a parent never shadows a child (GuzzleHttp\ must
// not swallow GuzzleHttp\Psr7\).
uksort(
	$map,
	static function ( $a, $b ) {
		return strlen( $b ) <=> strlen( $a );
	}
);

// Function files (Guzzle and friends) must be required eagerly.
$includes = array();
foreach ( $files as $file ) {
	$real = realpath( $file );
	if ( false !== $real && 0 === strncmp( $real, $real_base, strlen( $real_base ) ) ) {
		$includes[] = substr( $real, strlen( $real_base ) );
	}
}

if ( ! isset( $map['Square\\'] ) ) {
	fwrite( STDERR, "Scoped autoload map is missing the Square SDK; refusing to write.\n" );
	exit( 1 );
}

$generated = "<?php\n"
	. "// Generated by tools/fix-scoped-autoload.php. Do not edit.\n"
	. '$sqtwc_map = ' . var_export( $map, true ) . ";\n"
	. '$sqtwc_includes = ' . var_export( $includes, true ) . ";\n"
	. <<<'PHP_AUTOLOAD'

foreach ($sqtwc_includes as $sqtwc_include) {
    $sqtwc_file = __DIR__ . $sqtwc_include;
    if (is_file($sqtwc_file)) {
        require_once $sqtwc_file;
    }
}

spl_autoload_register(static function (string $class) use ($sqtwc_map): void {
    $prefix = 'WCPOS\\WooCommercePOS\\SquareTerminal\\Vendor\\';
    if (0 !== strncmp($class, $prefix, strlen($prefix))) {
        return;
    }
    $relative = substr($class, strlen($prefix));
    foreach ($sqtwc_map as $namespace => $dirs) {
        if (0 !== strncmp($relative, $namespace, strlen($namespace))) {
            continue;
        }
        $path = str_replace('\\', '/', substr($relative, strlen($namespace))) . '.php';
        foreach ($dirs as $dir) {
            $file = __DIR__ . $dir . '/' . $path;
            if (is_file($file)) {
                require $file;
                return;
            }
        }
    }
});
PHP_AUTOLOAD;

$target = $vendor_scoped . '/autoload.php';
if ( false === file_put_contents( $target, $generated ) ) {
	$error = error_get_last();
	fwrite( STDERR, 'Failed writing scoped autoload: ' . $target . ' ' . ( $error['message'] ?? '' ) . PHP_EOL );
	exit( 1 );
}

// Smoke-test the generated loader. Every class the plugin constructs at runtime
// must resolve, including a concrete PSR-18 client — without this the build can
// ship an autoloader that only fails on the first real Square request.
$required = array(
	'WCPOS\\WooCommercePOS\\SquareTerminal\\Vendor\\Square\\SquareClient',
	'WCPOS\\WooCommercePOS\\SquareTerminal\\Vendor\\GuzzleHttp\\Client',
	'WCPOS\\WooCommercePOS\\SquareTerminal\\Vendor\\GuzzleHttp\\Psr7\\Request',
);

$check = 'require ' . var_export( $target, true ) . ';'
	. 'foreach (' . var_export( $required, true ) . ' as $c) {'
	. 'if (!class_exists($c)) { fwrite(STDERR, "unloadable: " . $c . "\n"); exit(1); } }'
	. '$cls = "WCPOS\\\\WooCommercePOS\\\\SquareTerminal\\\\Vendor\\\\GuzzleHttp\\\\Client";'
	// The PSR interface is prefixed by php-scoper too, so the client must satisfy
	// the *scoped* ClientInterface — that is what the Square SDK type-hints.
	. '$iface = "WCPOS\\\\WooCommercePOS\\\\SquareTerminal\\\\Vendor\\\\Psr\\\\Http\\\\Client\\\\ClientInterface";'
	. '$g = new $cls();'
	. 'if (!($g instanceof $iface)) { fwrite(STDERR, "not PSR-18\n"); exit(1); }';

$output = array();
$status = 0;
exec( escapeshellarg( PHP_BINARY ) . ' -r ' . escapeshellarg( $check ) . ' 2>&1', $output, $status );

if ( 0 !== $status ) {
	fwrite( STDERR, "Scoped autoload smoke test failed:\n" . implode( "\n", $output ) . "\n" );
	exit( 1 );
}

echo "Scoped autoload written and verified.\n";
